---
name: Release

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Read version to environment
        run: echo "VERSION=$(cat resources/CONJTEST_VERSION)" >> $GITHUB_ENV
      - name: Read architecture to environment
        run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV
      - name: Install babashka
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.11.3.1463
          bb: 1.3.190
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Debug
        run: go version && uname -a
      - name: Build pod-ilmoraunio-conftest
        run: |
          cd pod-ilmoraunio-conjtest/pod-ilmoraunio-conftest && go install && go build
          cd ../../pod-ilmoraunio-conftest && go install && go build
      - name: Build pod-ilmoraunio-conjtest
        run: |
          cd pod-ilmoraunio-conjtest
          bb uberjar target/pod-ilmoraunio-conjtest.jar -m pod-ilmoraunio-conjtest.core
          cat $(which bb) target/pod-ilmoraunio-conjtest.jar > pod-ilmoraunio-conjtest && chmod +x pod-ilmoraunio-conjtest
      - name: Build conjtest
        run: |
          bb uberjar target/conjtest.jar -m conjtest.bb.main
          cat $(which bb) target/conjtest.jar > conjtest
          chmod +x conjtest
      - name: babashka & CLI tests
        run: ./scripts/test
      - name: Debug
        run: ls -lart
      - name: Produce artifact
        run: zip conjtest-$VERSION-macos-$ARCH.zip conjtest
      - name: Release artifact
        run: bb --config bb.ci.edn release-artifact --file conjtest-$VERSION-macos-$ARCH.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Read version to environment
        run: echo "VERSION=$(cat resources/CONJTEST_VERSION)" >> $GITHUB_ENV
      - name: Read architecture to environment
        run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV
      - name: Install babashka
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.11.3.1463
          bb: 1.3.190
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Debug
        run: go version && uname -a
      - name: Build pod-ilmoraunio-conftest
        run: |
          cd pod-ilmoraunio-conjtest/pod-ilmoraunio-conftest && go install && go build
          cd ../../pod-ilmoraunio-conftest && go install && go build
      - name: Build pod-ilmoraunio-conjtest
        run: |
          cd pod-ilmoraunio-conjtest
          bb uberjar target/pod-ilmoraunio-conjtest.jar -m pod-ilmoraunio-conjtest.core
          cat $(which bb) target/pod-ilmoraunio-conjtest.jar > pod-ilmoraunio-conjtest && chmod +x pod-ilmoraunio-conjtest
      - name: Build conjtest
        run: |
          bb uberjar target/conjtest.jar -m conjtest.bb.main
          cat $(which bb) target/conjtest.jar > conjtest
          chmod +x conjtest
      - name: babashka & CLI tests
        run: ./scripts/test
      - name: Debug
        run: ls -lart
      - name: Produce artifact
        run: tar -czvf conjtest-$VERSION-linux-$ARCH.tar.gz conjtest
      - name: Release artifact
        run: bb --config bb.ci.edn release-artifact --file conjtest-$VERSION-linux-$ARCH.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
